### ISSUE TITLE
Figure out client authentication workflow

### ISSUE THREAD

**Issue by GabeIsman** [mediapublic/mediapublic#97]
There should be a way to log in through the client, and the client should be sending cookies (or Javascript Web Tokens, or something similar) to the server. This is not currently working.

**Comment by GabeIsman** [comment]
Note that it doesn't seem as though authentication is working for me at all right now, I get the following error when I click the 'login with Twitter' link on /login.

```
----------------------------------------
2015-11-17 18:53:19,914 INFO  [requests.packages.urllib3.connectionpool][worker 6] Starting new HTTPS connection (1): api.twitter.com
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52193)
Traceback (most recent call last):
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/urlmap.py", line 216, in __call__
    return app(environ, start_response)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/pyramid/config/views.py", line 503, in _requestonly_view
    response = getattr(view, attr)(request)
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/velruse/providers/twitter.py", line 88, in login
    resp.status_code, resp.content))
velruse.exceptions.ThirdPartyFailure: Status 401: b'{"errors":[{"code":32,"message":"Could not authenticate you."}]}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 324, in wsgi_execute
    self.wsgi_write_chunk("Internal Server Error\n")
  File "/Users/gabe/Envs/mediapublic/lib/python3.5/site-packages/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 589, in write
    return self._sock.send(b)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by thequbit** [comment]
So this error pops up when you don't have valid twitter keys in your .ini file ( `provider.twitter.consumer_key` and `provider.twitter.consumer_secret` ).  You can get these at apps.twitter.com.

Not sure if there is a really elegant way to report this better, but I suppose we could throw an exception in the **init**.py file.

**Comment by GabeIsman** [comment]
Seems like the best place to report that would be would be when a login is actually attempted, or when the above error is thrown. We shouldn't require every developer to go through that flow if they don't need to work on login/logged-in functionality.

**Comment by nkkl** [comment]
Taking the "design" tag off of this because it doesn't appear to be a UX design task.

**Comment by GabeIsman** [comment]
I've made a start on this, but currently blocked by #147.
